### ISSUE TITLE
AddIdentity vs AddDefaultIdentity

### ISSUE THREAD

**Issue by Rakshasas** [gpeipman/AspNetCoreTests#1]
In your Startup.cs, you are using `services.AddDefaultIdentity<IdentityUser>`, however I am working on a project that does not use the DefaultUI or RazorPages so we are using `services.AddIdentity<IdentityUser,IdentityRole>`. If you make a similar change to your Startup, your integration tests will fail where they require authorization.

I can't understand this behaviour, and it's the only thing holding me back now from fully embracing Integration Tests. I am hoping you might understand why because my research on the subject hasn't yeilded any information as to why this could be.

My suspicion is because of the IdentityRole piece, and I've found a few posts complaining that there is no "AddDefaultIdentity" that omits the DefaultUI invocation.

**Comment by gpeipman** [comment]
How tests are failing? What are the exceptions you get?

**Comment by Rakshasas** [comment]
For example, the test Get_EditReturnsFailToRegularUser. Both `/Customers/Edit/` and `/Customers/Edit/1` fail because it is receiving a 302 redirect instead of being forbidden. They should be logged in with user claims but be forbidden.

The actually message from the test:

```
Tests.CustomerControllerTests.Get_EditReturnsFailToRegularUser(url: "/Customers/Edit/")
   Source: CustomerControllerTests.cs line 18
   Duration: 29 ms

  Message: 
    Assert.Equal() Failure
    Expected: Forbidden
    Actual:   Redirect
  Stack Trace: 
    CustomerControllerTests.Get_EditReturnsFailToRegularUser(String url) line 24
    --- End of stack trace from previous location where exception was thrown ---

```

The redirect implies they are being sent to the login.

However, using the original `services.AddDefaultIdentity<IdentityUser>` this does not happen and the tests pass. There is something different about the injected services when using `services.AddIdentity<IdentityUser,IdentityRole>`.

**Comment by Rakshasas** [comment]
I should also add that I do understand that changing the services would mean that the IdentityUI from Razor Pages is missing from your example, and the actual application wouldn't work properly as a result.

However I have a project where the Identity was custom made, and is using `services.AddIdentity<IdentityUser,IdentityRole>`. If I change that project to use `services.AddDefaultIdentity<IdentityUser>` the integration tests I created based on your example work, but it means that the DefaultUI Razor pages are included but dormant in my project. I'd rather not have them at all which is why I am trying to understand what is going on between `services.AddDefaultIdentity<IdentityUser>` and `services.AddIdentity<IdentityUser,IdentityRole>`.

From what I read, people would very much like it if an `AddDefaultIdentity` was available excluding the DefaultUi, but that is not the case.

**Comment by Rakshasas** [comment]
Sorry, I am not sure what happened when I posted this. I had been looking over so many examples and posts and somehow when I reached out I had to have been extremely confused.

Your `Startup.cs` does not even have a `services.AddDefaultIdentity<IdentityUser>();` This means I was referencing some other example, which is frankly just a mistake. Not sure what I was thinking.

Sorry for the confusion.
